name: CI

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  ci_workflow:
    uses: ./.github/workflows/ci.yml
  publish_to_hex:
    name: "Publish to Hex"
    runs-on: ubuntu-latest
    needs: [ci_workflow]
    steps:
      - run: |
          mix hex.config api_key ${{ secrets.HEX_API_KEY }}
          mix hex.publish --yes
